In [1]:
import pandas as pd

In [11]:
train_df = pd.read_csv(
    "../data/train.csv"
)

test_df = pd.read_csv(
    "../data/test.csv"
)

In [18]:
train_df.head()

,Index,geohash,day,timestamp,demand,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,48,0:0,0.048804,NaN,1,Not Allowed,No,NaN,NaN
1,1,qp02zt,48,0:0,0.118507,Residential,3,Allowed,Yes,31.104565,Sunny
2,2,qp08bj,48,0:0,0.027132,Residential,1,Not Allowed,No,25.919267,Sunny
3,3,qp08gt,48,0:0,0.003272,Residential,1,Not Allowed,No,NaN,Rainy
4,4,qp02zq,48,0:0,0.010819,Residential,1,Not Allowed,No,10.803667,Rainy

In [19]:
test_df.head()

,Index,geohash,day,timestamp,RoadType,NumberofLanes,LargeVehicles,Landmarks,Temperature,Weather
0,0,qp02z1,49,2:15,NaN,1,Not Allowed,No,NaN,NaN
1,1,qp02z9,49,2:15,Residential,1,Not Allowed,No,6.476213,Snowy
2,2,qp02yf,49,2:15,Residential,3,Allowed,Yes,22.318203,Sunny
3,3,qp02z6,49,2:15,Residential,2,Not Allowed,Yes,NaN,Rainy
4,4,qp02zd,49,2:15,Residential,1,Not Allowed,No,18.266162,Foggy

In [20]:
print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)

Train shape: (77299, 11)
Test shape: (41778, 10)

In [21]:
print("TRAIN NULL VALUES")
print(train_df.isnull().sum())

print("\nTEST NULL VALUES")
print(test_df.isnull().sum())

TRAIN NULL VALUES
Index               0
geohash             0
day                 0
timestamp           0
demand              0
RoadType          600
NumberofLanes       0
LargeVehicles       0
Landmarks           0
Temperature      2495
Weather           797
dtype: int64

TEST NULL VALUES
Index               0
geohash             0
day                 0
timestamp           0
RoadType          324
NumberofLanes       0
LargeVehicles       0
Landmarks           0
Temperature      1349
Weather           431
dtype: int64

In [25]:
train_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 77299 entries, 0 to 77298
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          77299 non-null  int64
 1   geohash        77299 non-null  str
 2   day            77299 non-null  int64
 3   timestamp      77299 non-null  str
 4   demand         77299 non-null  float64
 5   RoadType       76699 non-null  str
 6   NumberofLanes  77299 non-null  int64
 7   LargeVehicles  77299 non-null  str
 8   Landmarks      77299 non-null  str
 9   Temperature    74804 non-null  float64
 10  Weather        76502 non-null  str
dtypes: float64(2), int64(3), str(6)
memory usage: 6.5 MB

In [26]:
test_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 41778 entries, 0 to 41777
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Index          41778 non-null  int64
 1   geohash        41778 non-null  str
 2   day            41778 non-null  int64
 3   timestamp      41778 non-null  str
 4   RoadType       41454 non-null  str
 5   NumberofLanes  41778 non-null  int64
 6   LargeVehicles  41778 non-null  str
 7   Landmarks      41778 non-null  str
 8   Temperature    40429 non-null  float64
 9   Weather        41347 non-null  str
dtypes: float64(1), int64(3), str(6)
memory usage: 3.2 MB

In [29]:
train_df.describe()

              Index           day        demand  NumberofLanes   Temperature
count  77299.000000  77299.000000  7.729900e+04   77299.000000  74804.000000
mean   38649.000000     48.101838  9.394238e-02       2.014334     16.405354
std    22314.443566      0.302438  1.421905e-01       0.904665      7.359835
min        0.000000     48.000000  6.245650e-07       1.000000    -14.935097
25%    19324.500000     48.000000  1.822723e-02       1.000000     11.430473
50%    38649.000000     48.000000  4.775994e-02       2.000000     16.382587
75%    57973.500000     48.000000  1.085951e-01       3.000000     21.298833
max    77298.000000     49.000000  1.000000e+00       5.000000     48.251433

In [30]:
test_df.describe()

             Index      day  NumberofLanes   Temperature
count  41778.00000  41778.0   41778.000000  40429.000000
mean   20888.50000     49.0       2.068984     16.457339
std    12060.41411      0.0       0.988519      7.351067
min        0.00000     49.0       1.000000    -21.314645
25%    10444.25000     49.0       1.000000     11.527029
50%    20888.50000     49.0       2.000000     16.471232
75%    31332.75000     49.0       3.000000     21.365883
max    41777.00000     49.0       5.000000     45.230408